---
title: Dharma Siblings
description: A shared resource for our online sangha
remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/dharmaSiblings.png"
logo_width: 80
color_scheme: light

nav:
  - title: Liturgy
    url: /pages/liturgy
  - title: Video and Film
    url: /pages/video-and-film
  - title: Artwork
    url: /pages/artwork
  - title: Literature
    url: /pages/literature
  - title: Recipes
    url: /pages/recipes

just_the_docs:
  custom_css:
    - "/assets/css/just-the-docs.scss"

exclude:
  - AGENTS.md
  - CHANGELOG.md
  - CONTRIBUTING.md
  - README.md
  - SECURITY.md

defaults:
  - scope:
      path: "AGENTS.md"
    values:
      nav_exclude: true
      search_exclude: true
  - scope:
      path: "CHANGELOG.md"
    values:
      nav_exclude: true
      search_exclude: true
